"""initial schema

Revision ID: 3f17f49a2ecf
Revises: 
Create Date: 2026-05-27 18:58:08.333295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f17f49a2ecf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('badge_image_url', sa.String(length=500), nullable=True),
    sa.Column('achievement_type', sa.String(length=50), nullable=False),
    sa.Column('threshold_value', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('achievement_type'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cms_banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('placement', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('india_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('is_union_territory', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('india_districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['india_states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'state_id', name='uq_district_name_state')
    )
    with op.batch_alter_table('india_districts', schema=None) as batch_op:
        batch_op.create_index('ix_district_state_id', ['state_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('suspension_reason', sa.Text(), nullable=True),
    sa.Column('preferred_state_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['preferred_state_id'], ['india_states.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('admin_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_activity_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_admin_logs_admin_user_id', ['admin_user_id'], unique=False)
        batch_op.create_index('ix_admin_logs_created_at', ['created_at'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_logs_user_id', ['user_id'], unique=False)

    op.create_table('cms_articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('slug', sa.String(length=450), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('article_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cms_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cms_articles_article_type'), ['article_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_cms_articles_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_cms_articles_status'), ['status'], unique=False)
        batch_op.create_index('ix_cms_articles_status_type', ['status', 'article_type'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('identification_complete', sa.Boolean(), nullable=False),
    sa.Column('new_species_nearby', sa.Boolean(), nullable=False),
    sa.Column('admin_verification', sa.Boolean(), nullable=False),
    sa.Column('educational_alerts', sa.Boolean(), nullable=False),
    sa.Column('events', sa.Boolean(), nullable=False),
    sa.Column('fcm_token', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index('ix_notifications_user_id', ['user_id'], unique=False)

    op.create_table('species',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('common_name', sa.String(length=200), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=False),
    sa.Column('family', sa.String(length=100), nullable=False),
    sa.Column('genus', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('habitat', sa.Text(), nullable=True),
    sa.Column('seasonal_appearance', sa.JSON(), nullable=True),
    sa.Column('conservation_status', sa.String(length=5), nullable=False),
    sa.Column('wing_span_min_mm', sa.Integer(), nullable=True),
    sa.Column('wing_span_max_mm', sa.Integer(), nullable=True),
    sa.Column('is_migratory', sa.Boolean(), nullable=False),
    sa.Column('color_tags', sa.JSON(), nullable=True),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_species_conservation_status'), ['conservation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_species_family'), ['family'], unique=False)
        batch_op.create_index(batch_op.f('ix_species_scientific_name'), ['scientific_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_species_slug'), ['slug'], unique=True)

    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement_definitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index('ix_user_achievements_user_id', ['user_id'], unique=False)

    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('total_observations', sa.Integer(), nullable=False),
    sa.Column('total_identifications', sa.Integer(), nullable=False),
    sa.Column('total_species_observed', sa.Integer(), nullable=False),
    sa.Column('total_states_explored', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_observation_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('species_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('weather', sa.String(length=30), nullable=True),
    sa.Column('butterfly_activity', sa.String(length=30), nullable=True),
    sa.Column('count_observed', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location_name', sa.String(length=500), nullable=True),
    sa.Column('privacy', sa.String(length=20), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['india_districts.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['india_states.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index('ix_observations_district_id', ['district_id'], unique=False)
        batch_op.create_index('ix_observations_observed_at', ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_privacy'), ['privacy'], unique=False)
        batch_op.create_index('ix_observations_species_id', ['species_id'], unique=False)
        batch_op.create_index('ix_observations_state_id', ['state_id'], unique=False)
        batch_op.create_index('ix_observations_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_verification_status'), ['verification_status'], unique=False)

    op.create_table('species_host_plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.String(length=36), nullable=False),
    sa.Column('plant_name', sa.String(length=200), nullable=False),
    sa.Column('plant_scientific_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('species_host_plants', schema=None) as batch_op:
        batch_op.create_index('ix_host_plants_species_id', ['species_id'], unique=False)

    op.create_table('species_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('species_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('image_type', sa.String(length=30), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('credit', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('species_images', schema=None) as batch_op:
        batch_op.create_index('ix_species_images_species_id', ['species_id'], unique=False)

    op.create_table('species_india_distribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.String(length=36), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('abundance', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['india_states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('species_id', 'state_id', name='uq_species_state')
    )
    with op.batch_alter_table('species_india_distribution', schema=None) as batch_op:
        batch_op.create_index('ix_species_distribution_species_id', ['species_id'], unique=False)
        batch_op.create_index('ix_species_distribution_state_id', ['state_id'], unique=False)

    op.create_table('identification_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_gemini_response', sa.JSON(), nullable=True),
    sa.Column('gemini_raw_text', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('gemini_model_version', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id')
    )
    with op.batch_alter_table('identification_results', schema=None) as batch_op:
        batch_op.create_index('ix_id_results_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_id_results_status', ['status'], unique=False)
        batch_op.create_index('ix_id_results_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identification_results_status'), ['status'], unique=False)

    op.create_table('observation_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('original_url', sa.String(length=500), nullable=False),
    sa.Column('optimized_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observation_images', schema=None) as batch_op:
        batch_op.create_index('ix_obs_images_observation_id', ['observation_id'], unique=False)

    op.create_table('public_shares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id')
    )
    with op.batch_alter_table('public_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_shares_share_token'), ['share_token'], unique=True)

    op.create_table('identification_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identification_result_id', sa.String(length=36), nullable=False),
    sa.Column('species_id', sa.String(length=36), nullable=True),
    sa.Column('matched_common_name', sa.String(length=200), nullable=True),
    sa.Column('matched_scientific_name', sa.String(length=200), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['identification_result_id'], ['identification_results.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identification_matches', schema=None) as batch_op:
        batch_op.create_index('ix_id_matches_result_id', ['identification_result_id'], unique=False)
        batch_op.create_index('ix_id_matches_species_id', ['species_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identification_matches', schema=None) as batch_op:
        batch_op.drop_index('ix_id_matches_species_id')
        batch_op.drop_index('ix_id_matches_result_id')

    op.drop_table('identification_matches')
    with op.batch_alter_table('public_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_shares_share_token'))

    op.drop_table('public_shares')
    with op.batch_alter_table('observation_images', schema=None) as batch_op:
        batch_op.drop_index('ix_obs_images_observation_id')

    op.drop_table('observation_images')
    with op.batch_alter_table('identification_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identification_results_status'))
        batch_op.drop_index('ix_id_results_user_id')
        batch_op.drop_index('ix_id_results_status')
        batch_op.drop_index('ix_id_results_created_at')

    op.drop_table('identification_results')
    with op.batch_alter_table('species_india_distribution', schema=None) as batch_op:
        batch_op.drop_index('ix_species_distribution_state_id')
        batch_op.drop_index('ix_species_distribution_species_id')

    op.drop_table('species_india_distribution')
    with op.batch_alter_table('species_images', schema=None) as batch_op:
        batch_op.drop_index('ix_species_images_species_id')

    op.drop_table('species_images')
    with op.batch_alter_table('species_host_plants', schema=None) as batch_op:
        batch_op.drop_index('ix_host_plants_species_id')

    op.drop_table('species_host_plants')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_verification_status'))
        batch_op.drop_index('ix_observations_user_id')
        batch_op.drop_index('ix_observations_state_id')
        batch_op.drop_index('ix_observations_species_id')
        batch_op.drop_index(batch_op.f('ix_observations_privacy'))
        batch_op.drop_index('ix_observations_observed_at')
        batch_op.drop_index('ix_observations_district_id')

    op.drop_table('observations')
    op.drop_table('user_streaks')
    op.drop_table('user_stats')
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_index('ix_user_achievements_user_id')

    op.drop_table('user_achievements')
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_species_slug'))
        batch_op.drop_index(batch_op.f('ix_species_scientific_name'))
        batch_op.drop_index(batch_op.f('ix_species_family'))
        batch_op.drop_index(batch_op.f('ix_species_conservation_status'))

    op.drop_table('species')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_id')
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index('ix_notifications_created_at')

    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    with op.batch_alter_table('cms_articles', schema=None) as batch_op:
        batch_op.drop_index('ix_cms_articles_status_type')
        batch_op.drop_index(batch_op.f('ix_cms_articles_status'))
        batch_op.drop_index(batch_op.f('ix_cms_articles_slug'))
        batch_op.drop_index(batch_op.f('ix_cms_articles_article_type'))

    op.drop_table('cms_articles')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_user_id')
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('admin_activity_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_logs_created_at')
        batch_op.drop_index('ix_admin_logs_admin_user_id')
        batch_op.drop_index(batch_op.f('ix_admin_activity_logs_created_at'))

    op.drop_table('admin_activity_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('india_districts', schema=None) as batch_op:
        batch_op.drop_index('ix_district_state_id')

    op.drop_table('india_districts')
    op.drop_table('roles')
    op.drop_table('india_states')
    op.drop_table('cms_banners')
    op.drop_table('achievement_definitions')
    # ### end Alembic commands ###
