"""add_token_fields_to_identification_results

Revision ID: 74e5a4c923ca
Revises: 9c7fc0c5ac7f
Create Date: 2026-07-16 14:13:30.998699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74e5a4c923ca'
down_revision = '9c7fc0c5ac7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identification_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_token_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('output_token_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_token_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identification_results', schema=None) as batch_op:
        batch_op.drop_column('total_token_count')
        batch_op.drop_column('output_token_count')
        batch_op.drop_column('input_token_count')
    # ### end Alembic commands ###
