"""add observation likes and comments tables

Revision ID: 9c7fc0c5ac7f
Revises: 3f17f49a2ecf
Create Date: 2026-07-03 11:07:16.777799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7fc0c5ac7f'
down_revision = '3f17f49a2ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observation_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observation_comments', schema=None) as batch_op:
        batch_op.create_index('ix_comments_observation_id', ['observation_id'], unique=False)

    op.create_table('observation_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id', 'user_id', name='uq_like_obs_user')
    )
    with op.batch_alter_table('observation_likes', schema=None) as batch_op:
        batch_op.create_index('ix_likes_observation_id', ['observation_id'], unique=False)

    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    with op.batch_alter_table('observation_likes', schema=None) as batch_op:
        batch_op.drop_index('ix_likes_observation_id')

    op.drop_table('observation_likes')
    with op.batch_alter_table('observation_comments', schema=None) as batch_op:
        batch_op.drop_index('ix_comments_observation_id')

    op.drop_table('observation_comments')
    # ### end Alembic commands ###
